<?php

function import_recipes_menu(){
   $items['recipes.xml'] = array(
        'title' => 'menu',
        'page callback' => 'import_recipe_xml',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['test.xml'] = array(
        'title' => 'menu',
        'page callback' => 'import_test',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
	return $items;
}

function import_test(){
  $node = node_load(8);
  dsm(import_recipes_get_recipes());  
  return "";
}

function import_recipe_xml() {
    drupal_add_http_header('Content-type', 'application/xhtml+xml; charset=utf-8');
    $nodes = import_recipes_get_recipes();
    echo theme('import_recipe', array(
        "nodes" => $nodes,
    ));
    drupal_exit();
}

function import_recipes_get_recipes(){
  $nodes = db_select('node', 'n')
  	->fields('n')	 
       ->condition('n.type', 'dieta_recipe')
	->execute();
  $items = array(); 
  foreach ($nodes as $node) {
     $items[] = import_recipes_get_array_recipe(node_load($node->nid));   
  }   
  return $items;
}

function import_recipes_get_array_recipe($node){
   $recipe = array();
   $recipe['name']=$node->title;
   $recipe['url']= "http://dieta-abc.ru/node/" . $node->nid;
   $recipe['type']=import_recipes_get_type_recipe($node);
   $recipe['ingredients']= $node->dieta_recipe_ingredients['ing'];
   $recipe['instructions']=import_recipes_get_instructions_recipe($node);

   return $recipe;
}

function import_recipes_get_type_recipe($node){
    $term = taxonomy_term_load($node->field_recipe_classifier['und']['0']['tid']);   
    return $term->name;    
}


function import_recipes_get_instructions_recipe($node){
    $instruction = array();
    $field_instruction = field_get_items('node',$node,'field_recipe_steps');
    foreach($field_instruction as $key=>$value){
	$field_desctription = entity_load('field_collection_item', array($value['value']));	
       $instruction[] = $field_desctription[$value['value']]->field_recipe_step_desc['und']['0']['value'];
    }
    return $instruction;
}


function import_recipes_theme() {
    return array(
        'import_recipe' => array(
            'template' => 'templates/import_recipes',                  
            'variables' => array(
                'nodes' => NULL,              
            ), 
        ),
    );
}